[package]
name = "spectrusty_utils"
version = "0.1.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2018"

[dependencies]
spectrusty_formats = { path = "../spectrusty_formats", version = "0.1" }
