language: rust
os: linux
dist: bionic
addons:
    apt:
        packages:
            - libssl-dev
            - libasound2-dev
rust:
  - 1.41.0
  - 1.42.0
  - stable
  - beta
  - nightly
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo test --verbose -- --ignored
      cargo test --no-default-features --verbose
      cargo test --no-default-features --verbose -- --ignored
      cargo build -p zxspectrum-common --verbose
      cargo test -p zxspectrum-common --verbose
      cargo build -p audio --bins --verbose
      cargo test -p audio --verbose
    fi
