[package]
name = "zxspecemu"
version = "0.1.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
smallvec = "1.1.0"
cpal = "0.11.0"
hound = "3.4.0"
simple_logger = "1.3.0"

[dependencies]
z80emu = "0.1.0"
log = "0.4.8"
derive_more = "0.99.2"
bitflags = "1.2.1"
nom = "5.1.0"
memchr = "2.3.0"
