[package]
name = "zxspecemu"
version = "0.1.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2018"

[features]
default = ["snapshot"]
snapshot = ["serde", "arrayvec/serde", "z80emu/serde"]

[dev-dependencies]
smallvec = "1.1.0"
cpal = "0.11.0"
hound = "3.4.0"
simple_logger = "1.6.0"
serde_json = "1.0"
bincode = "1.2"

[dependencies.serde]
default-features = true
features = ["derive"]
optional = true
version = "1.0"

[dependencies.z80emu]
default-features = false
features = ["std"]
version = "0.2.0"
# path = "../z80emu"

[dependencies]
log = "0.4"
derive_more = "0.99.2"
arrayvec = "0.5.1"
bitflags = "1.2.1"
nom = "5.1.0"
memchr = "2.3.0"
rand = {version = "0.7", features = ["small_rng"]}
bitvec = "0.17.3"
base64 = "0.12.0"

[workspace]
members = [
  "examples/web_ay_player",
  "examples/sdl2_zxspectrum"
]
