[package]
name = "spectrusty_audio"
version = "0.1.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2018"

[dependencies]
spectrusty_core = { path = "../spectrusty_core", version = "0.1" }
